version: "3"
services:
  redis:
    image: "redis:alpine"
  db:
    image: "postgres:11"
    container_name: "my_database"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  static:
    env_file: 
      - .env
    build: .
    command: "python manage.py collectstatic --noinput"
  web:
    env_file: 
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery:
    build: .
    env_file: 
      - .env
    command: "celery -A GameMuster worker -l info"
    depends_on:
      - web
      - static
  celery-beat:
    build: .
    env_file: 
      - .env
    command: "celery -A GameMuster beat -l info"
    depends_on:
      - web
volumes:
  my_dbdata:
